### ISSUE TITLE
Repeatedly pressing 'Start' on the clock breaks it

### ISSUE THREAD

**Issue by dbxnr** [diarmuidmorgan/burger_restaurant#2]
Looks like it opens multiple instances of the timer or something, and pressing 'Stop' can't close them.

**Comment by diarmuidmorgan** [comment]
Oh no. Best to avoid that anyway

**Comment by dbxnr** [comment]
>     this.start = function () {
>         clearInterval(this.c) // Adding a line to stop the clock before starting it fixed this.
>         this.c = setInterval(this.increment, GAME_SPEED);
>     }
